// Comprehensive TypeScript interfaces for the PPL Data system
// Based on actual database schema discovered during testing

export interface PPLIndex {
  id: number;
  name: string;
  tier: 'hard' | 'soft' | 'base';
  weak?: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface LegiIndex {
  id: number;
  name: string | null;
  sub_name: string | null;
  bill_lvl?: string;
  indexed?: boolean;
  weak?: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface PPLProfiles {
  index_id: number;
  created_at?: string;
  updated_at?: string;
  
  // Synopsis fields (generated by AI)
  synopsis?: string;      // 150-200 words
  agenda?: string;        // 100-150 words  
  identity?: string;      // 100-150 words
  affiliates?: string;    // 100-150 words
  
  // Metrics (refreshed weekly)
  approval?: number;      // 0-100
  disapproval?: number;   // 0-100
  votes?: number;         // Total vote count
  poll_summary?: string;  // Brief poll description
  poll_link?: string;     // Source URL
}

export interface CardIndex {
  id: number;
  owner_id: number;
  created_at: string;
  is_active: boolean;
  is_ppl: boolean;        // Always true for politician cards
  
  // Content metadata
  title: string;
  subtext: string;
  screen: 'agenda_ppl' | 'identity' | 'affiliates';
  category?: string;      // For hard/soft tiers
  score: number;          // 0-100 relevance score
  is_media: boolean;
  link: string;           // Source URL
}

export interface CardContent {
  id: number;
  card_id: number;
  title: string;
  link1: string;          // Primary source
  link2?: string;         // Secondary source
  link3?: string;         // Tertiary source
  web_content: string;    // Extracted content
  body_text?: string;     // Processed text
  tldr?: string;          // AI-generated summary
  legi_text?: string;     // Legislative text
  created_at: string;
  updated_at?: string;
}

export interface Bookmarks {
  id: number;
  user_id: string;
  owner_id: number;       // References card_index.id
  bookmark_type: 'card' | 'profile';
  created_at: string;
}

// Tier configurations with exact quotas
export const TIER_CONFIG = {
  hard: {
    categories: [
      'economy', 'immigration', 'healthcare', 'environment', 'defense', 'education',
      'background', 'career', 'public image', 'accomplishments', 'statements', 'awards',
      'party', 'organizations', 'businesses', 'politicians', 'medias', 'donors'
    ],
    quotas: {
      named: 10,           // 18 categories × 10 each = 180 cards
      more: 10            // 3 more buckets × 10 each = 30 cards (agenda_ppl, identity, affiliates)
    }
  },
  soft: {
    categories: [
      'economy', 'social programs', 'immigration', 'national security',
      'background', 'career', 'public image', 'beliefs', 'party', 
      'politicians', 'enterprises', 'donors'
    ],
    quotas: {
      named: 6            // 12 categories × 6 each = 72 cards
    }
  },
  base: {
    screens: ['agenda_ppl', 'identity', 'affiliates'],
    quotas: {
      screen: 10          // 3 screens × 10 each = 30 cards
    }
  }
} as const;

// Screen mapping for categories
export const SCREEN_MAPPING = {
  agenda_ppl: ['economy', 'immigration', 'healthcare', 'environment', 'defense', 'education', 'more'],
  identity: ['background', 'career', 'public image', 'accomplishments', 'statements', 'awards', 'more'],
  affiliates: ['party', 'organizations', 'businesses', 'politicians', 'medias', 'donors', 'enterprises', 'more']
} as const;

// Search and extraction types
export interface TavilySearchResult {
  title: string;
  url: string;
  content: string;
  score: number;
  published_date?: string;
}

export interface ExtractedContent {
  url: string;
  title: string;
  content: string;
  wordCount: number;
  isOfficial: boolean;
  domain: string;
}

export interface CardPreview {
  title: string;
  subtext: string;
  category: string;
  screen: string;
  score: number;
  link: string;
  content: string;
}

// Quota tracking types
export interface QuotaDeficit {
  screen: string;
  category?: string;
  current: number;
  target: number;
  deficit: number;
}

export interface QuotaStatus {
  ownerId: number;
  tier: string;
  deficits: QuotaDeficit[];
  totalDeficit: number;
}

// AI model types
export type MistralModel = 'mistral-small-latest' | 'mistral-large-latest';

export interface AIRequest {
  model: MistralModel;
  prompt: string;
  maxTokens?: number;
  temperature?: number;
}

// Error handling types
export interface PPLDataError {
  code: string;
  message: string;
  context?: any;
  timestamp: string;
}

// Validation schemas
export const VALIDATION_RULES = {
  title: {
    minLength: 10,
    maxLength: 70,
    required: true
  },
  synopsis: {
    minWords: 15,
    maxWords: 25,
    required: false
  },
  agenda: {
    minWords: 35,
    maxWords: 45,
    required: false
  },
  identity: {
    minWords: 25,
    maxWords: 35,
    required: false
  },
  affiliates: {
    minWords: 20,
    maxWords: 30,
    required: false
  },
  approval: {
    min: 0,
    max: 100,
    required: false
  },
  disapproval: {
    min: 0,
    max: 100,
    required: false
  },
  score: {
    min: 0,
    max: 100,
    required: true
  }
} as const;

// Utility type guards
export function isValidTier(tier: string): tier is 'hard' | 'soft' | 'base' {
  return ['hard', 'soft', 'base'].includes(tier);
}

export function isValidScreen(screen: string): screen is 'agenda_ppl' | 'identity' | 'affiliates' {
  return ['agenda_ppl', 'identity', 'affiliates'].includes(screen);
}

export function isValidCategory(category: string, tier: string): boolean {
  if (tier === 'base') return true; // Base tier can have categories but doesn't need them
  return TIER_CONFIG[tier as keyof typeof TIER_CONFIG]?.categories?.includes(category) || false;
}

// Content validation
export function validateWordCount(text: string, minWords: number, maxWords: number): boolean {
  const wordCount = text.trim().split(/\s+/).length;
  return wordCount >= minWords && wordCount <= maxWords;
}

export function validateScore(score: number): boolean {
  return score >= 0 && score <= 100;
}

export function validateApprovalRating(rating: number): boolean {
  return rating >= 0 && rating <= 100;
}
