-- Migration: Baseline schema
-- Date: 2025-01-01 (backfilled 2026-07-13)
-- Description:
--   Captures the 16 core tables, enums, and shared trigger functions that were
--   built directly on the remote project (via Studio) before migration
--   tracking started, and were never represented by a CREATE TABLE migration.
--   Source: `supabase db dump --linked -s public`, run against the linked
--   project on 2026-07-13. Deliberately excludes `ppl_scores` and
--   `notifications` (and functions used only by them: call_bill_update,
--   insert_ppl_score, update_ppl_score, recompute_ppl_profile_score,
--   trg_ppl_scores_recompute_profile_score) since those already have their
--   own complete migration lineage elsewhere in this directory. Excludes
--   OWNER TO statements for portability across environments.

CREATE TYPE "public"."bill_lvl" AS ENUM (
    'nationwide',
    'statewide',
    'local'
);

CREATE TYPE "public"."bill_status" AS ENUM (
    'passed',
    'processing',
    'failed'
);

CREATE TYPE "public"."bookmark_type" AS ENUM (
    'ppl',
    'legi',
    'card'
);

CREATE TYPE "public"."card_owner_type" AS ENUM (
    'ppl',
    'legi'
);

CREATE TYPE "public"."card_placement_kind" AS ENUM (
    'preview',
    'category',
    'more_selections'
);

CREATE TYPE "public"."categories" AS ENUM (
    'economy',
    'immigration',
    'healthcare',
    'defense',
    'environment',
    'education',
    'background',
    'career',
    'public image',
    'accomplishments',
    'statements',
    'awards',
    'party',
    'organizations',
    'businesses',
    'politicians',
    'medias',
    'donors',
    'more',
    'social programs',
    'national security',
    'beliefs',
    'enterprises',
    'action',
    'scope',
    'process',
    'exceptions',
    'sectors',
    'demographics',
    'regions',
    'aftermath',
    'Backers',
    'Opposers',
    'Narratives',
    'Coverage',
    'backers',
    'opposers',
    'narratives',
    'coverage'
);

CREATE TYPE "public"."content_origin" AS ENUM (
    'gpt',
    'manual',
    'mixed'
);

CREATE TYPE "public"."gov_level" AS ENUM (
    'federal',
    'state',
    'city'
);

CREATE TYPE "public"."legi_page" AS ENUM (
    'agenda',
    'impact',
    'discourse'
);

CREATE TYPE "public"."legislation_status" AS ENUM (
    'introduced',
    'in_committee',
    'on_floor',
    'passed_one_chamber',
    'passed_both_chambers',
    'signed_law',
    'failed'
);

CREATE TYPE "public"."office_type" AS ENUM (
    'president',
    'vice_president',
    'senator',
    'representative',
    'governor',
    'mayor',
    'cabinet',
    'candidate',
    'official'
);

CREATE TYPE "public"."party_type" AS ENUM (
    'D',
    'R',
    'I',
    'other'
);

CREATE TYPE "public"."ppl_page" AS ENUM (
    'agenda',
    'identity',
    'affiliates'
);

CREATE TYPE "public"."screen_type" AS ENUM (
    'agenda_ppl',
    'agenda_legi',
    'identity',
    'affiliates',
    'impact',
    'discourse'
);

CREATE TYPE "public"."screens" AS ENUM (
    'agenda',
    'identity',
    'affiliates',
    'impact',
    'discourse'
);

CREATE TYPE "public"."tier" AS ENUM (
    'base',
    'soft',
    'hard'
);

-- Shared trigger functions (used by bookmarks / feedback / ratings / referrals / auth)

CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  insert into public.users (uuid, email, created_at)
  values (new.id, new.email, coalesce(new.created_at, now()))
  on conflict (uuid) do update
    set email = excluded.email;  -- don't touch created_at on updates
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."set_code_owner_text"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  new.code_owner := auth.uid()::text;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."set_user_id_text"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  new.user_id := auth.uid()::text;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."set_user_id_uuid"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  new.user_id := auth.uid();
  return new;
end;
$$;

-- Tables

CREATE TABLE IF NOT EXISTS "public"."bookmarks" (
    "id" bigint NOT NULL,
    "owner_id" bigint,
    "user_id" "text",
    "bookmark_type" "public"."bookmark_type",
    "created_at" timestamp without time zone
);
COMMENT ON TABLE "public"."bookmarks" IS 'who saved which profile';
ALTER TABLE "public"."bookmarks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bookmarks_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."card_content" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "card_id" bigint,
    "body_text" "text",
    "tldr" "text",
    "link1" "text",
    "title" "text",
    "excerpt" "text",
    "demographics" "text",
    "related" "text"
);
COMMENT ON TABLE "public"."card_content" IS 'page info and content for each card';
ALTER TABLE "public"."card_content" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."card_content_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."card_index" (
    "id" bigint NOT NULL,
    "title" "text",
    "subtext" "text",
    "created_at" timestamp without time zone,
    "owner_id" bigint,
    "opens_7d" smallint,
    "is_media" boolean,
    "category" "public"."categories",
    "is_ppl" boolean,
    "score" numeric,
    "screen" "public"."screen_type",
    "link" "text",
    "is_active" boolean,
    "web" "text",
    "slug" "text",
    "web_id" bigint,
    "bill_section" integer
);
COMMENT ON TABLE "public"."card_index" IS 'frontpage data for each card';

CREATE TABLE IF NOT EXISTS "public"."ppl_profiles" (
    "id" bigint NOT NULL,
    "index_id" bigint,
    "approval" "text",
    "disapproval" "text",
    "score" numeric,
    "weekly_visits" smallint,
    "poll_summary" "text",
    "poll_link" "text",
    "synopsis" "text",
    "agenda" "text",
    "identity" "text",
    "affiliates" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "votes" "text",
    "updated_at" timestamp without time zone DEFAULT "now"(),
    "votes_else" "text",
    "metrics_load" boolean
);
COMMENT ON TABLE "public"."ppl_profiles" IS 'live metadata on ppl';
COMMENT ON COLUMN "public"."ppl_profiles"."poll_summary" IS '14 - 160 characters';
ALTER TABLE "public"."ppl_profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."current ppl_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."feedback" (
    "id" bigint NOT NULL,
    "comment" "text",
    "created_at" timestamp without time zone,
    "user_id" "uuid",
    "source" "text",
    "userEmail" "text"
);
COMMENT ON TABLE "public"."feedback" IS 'user submitted profile feedback';
COMMENT ON COLUMN "public"."feedback"."source" IS 'Source of feedback: NULL for account page, "ppl{id}" or "legi{id}" for profile pages, "ppl{id}/{card_id}" or "legi{id}/{card_id}" for card pages';
ALTER TABLE "public"."feedback" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."feedback_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."impact" (
    "id" bigint NOT NULL,
    "card_id" bigint,
    "user_id" "uuid",
    "impact" "text",
    "onboard_snapshot" "text"
);
ALTER TABLE "public"."impact" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."impact_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."legi_index" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "sub_name" "text",
    "profile_visits" numeric,
    "bill_lvl" "public"."bill_lvl",
    "bill_status" "public"."bill_status",
    "scanned" integer,
    "bill_id" "text",
    "congress" "text",
    "indexed" boolean,
    "weak" boolean,
    "created_at" timestamp with time zone,
    "cosponsors" "text",
    "committees" "text",
    "subject" "text",
    "latest_action" "text",
    "actions" "text",
    "data_update" timestamp with time zone
);
COMMENT ON COLUMN "public"."legi_index"."profile_visits" IS 'Total number of times this legislation profile has been viewed (cumulative, never resets)';
ALTER TABLE "public"."legi_index" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."legi_index_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."legi_profiles" (
    "id" bigint NOT NULL,
    "overview" "text" NOT NULL,
    "agenda" "text",
    "impact" "text",
    "owner_id" "text"
);
COMMENT ON TABLE "public"."legi_profiles" IS 'data for overview page on legislation profiles';
ALTER TABLE "public"."legi_profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."legi_overview_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."ratings" (
    "id" bigint NOT NULL,
    "user_id" "text" NOT NULL,
    "profile_id" bigint,
    "rating" smallint,
    "created_at" timestamp without time zone,
    "type" "text"
);
COMMENT ON TABLE "public"."ratings" IS 'tracks who rated who';
ALTER TABLE "public"."ratings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."popularity_user_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE "public"."card_index" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ppl_agenda_cards_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."ppl_index" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "sub_name" "text",
    "gov_level" "public"."gov_level",
    "limit_score" real,
    "tier" "public"."tier",
    "party_type" "public"."party_type",
    "office_type" "public"."office_type",
    "slug" "text",
    "state_code" "text",
    "indexed" boolean,
    "weak" boolean,
    "opens" integer,
    "created_at" timestamp with time zone,
    "records" "text",
    "affiliates" "text",
    "related" "text"
);
COMMENT ON TABLE "public"."ppl_index" IS 'base info list on all officials';
ALTER TABLE "public"."ppl_index" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ppl_list_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."questions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "card_id" integer,
    "question" "text",
    "answer" "text"
);
ALTER TABLE "public"."questions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."q/a_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."referrals" (
    "id" bigint NOT NULL,
    "referral_code" "text",
    "code_owner" "text",
    "uses" bigint
);
COMMENT ON TABLE "public"."referrals" IS 'referral tracking';
ALTER TABLE "public"."referrals" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."referrals_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."requests" (
    "id" bigint NOT NULL,
    "user_id" bigint,
    "request" "text"
);
ALTER TABLE "public"."requests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."requests_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."subs" (
    "id" bigint NOT NULL,
    "profile_id" "text",
    "user" "text"
);
ALTER TABLE "public"."subs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."subs_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "plan" "text",
    "onboard" "text",
    "uuid" "uuid",
    "week_profiles" "text",
    "last_reset" timestamp with time zone,
    "cycle" "text",
    "email" "text",
    "last_transaction_id" "text",
    "last_purchase_date" timestamp without time zone,
    "receipt_validated" boolean DEFAULT false,
    "has_seen_founders_note" boolean DEFAULT false,
    "weak_profiles" "text",
    "plus_til" "text",
    "sub_logs" "text",
    "notifications_enabled" boolean DEFAULT true NOT NULL
);
COMMENT ON COLUMN "public"."users"."has_seen_founders_note" IS 'Tracks if user has seen the founder''s note (once per account, persists across devices)';
COMMENT ON COLUMN "public"."users"."notifications_enabled" IS 'Whether the user has enabled notifications in-app (independent of device permission status)';
ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."web_content" (
    "id" bigint NOT NULL,
    "path" "text",
    "owner_id" bigint,
    "is_ppl" boolean,
    "link" "text",
    "used" boolean
);
ALTER TABLE "public"."web_content" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."web_content_id_seq"
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- Primary / unique key constraints

ALTER TABLE ONLY "public"."bookmarks" ADD CONSTRAINT "bookmarks_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."card_content" ADD CONSTRAINT "card_content_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."ppl_profiles" ADD CONSTRAINT "current ppl_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."feedback" ADD CONSTRAINT "feedback_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."impact" ADD CONSTRAINT "impact_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."legi_index" ADD CONSTRAINT "legi_index_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."legi_profiles" ADD CONSTRAINT "legi_overview_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."ratings" ADD CONSTRAINT "popularity_user_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."card_index" ADD CONSTRAINT "ppl_agenda_cards_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."ppl_index" ADD CONSTRAINT "ppl_list_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."ppl_profiles" ADD CONSTRAINT "ppl_profiles_index_id_unique" UNIQUE ("index_id");
ALTER TABLE ONLY "public"."questions" ADD CONSTRAINT "q/a_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."referrals" ADD CONSTRAINT "referrals_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."requests" ADD CONSTRAINT "requests_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."subs" ADD CONSTRAINT "subs_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_uuid_unique" UNIQUE ("uuid");
ALTER TABLE ONLY "public"."web_content" ADD CONSTRAINT "web_content_pkey" PRIMARY KEY ("id");

-- Indexes

CREATE INDEX "idx_users_founders_note" ON "public"."users" USING "btree" ("has_seen_founders_note");

-- Triggers

CREATE OR REPLACE TRIGGER "t_set_code_owner_referrals" BEFORE INSERT ON "public"."referrals" FOR EACH ROW EXECUTE FUNCTION "public"."set_code_owner_text"();
CREATE OR REPLACE TRIGGER "t_set_user_id_bookmarks" BEFORE INSERT ON "public"."bookmarks" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id_text"();
CREATE OR REPLACE TRIGGER "t_set_user_id_feedback" BEFORE INSERT ON "public"."feedback" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id_text"();
CREATE OR REPLACE TRIGGER "t_set_user_id_ratings" BEFORE INSERT ON "public"."ratings" FOR EACH ROW EXECUTE FUNCTION "public"."set_user_id_text"();

-- Row level security

ALTER TABLE "public"."bookmarks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."card_content" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."card_index" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."legi_index" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."legi_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ppl_index" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ppl_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ratings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."referrals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."web_content" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read ppl_index" ON "public"."ppl_index" FOR SELECT USING (true);
CREATE POLICY "app_users auth insert" ON "public"."users" FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "app_users auth read" ON "public"."users" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "app_users auth update" ON "public"."users" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "bk delete own" ON "public"."bookmarks" FOR DELETE TO "authenticated" USING (("user_id" = ("auth"."uid"())::"text"));
CREATE POLICY "bk insert own" ON "public"."bookmarks" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = ("auth"."uid"())::"text"));
CREATE POLICY "bk select own" ON "public"."bookmarks" FOR SELECT TO "authenticated" USING (("user_id" = ("auth"."uid"())::"text"));
CREATE POLICY "bk update own" ON "public"."bookmarks" FOR UPDATE TO "authenticated" USING (("user_id" = ("auth"."uid"())::"text")) WITH CHECK (("user_id" = ("auth"."uid"())::"text"));
CREATE POLICY "fb insert own" ON "public"."feedback" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "auth"."uid"()));
CREATE POLICY "fb select own" ON "public"."feedback" FOR SELECT TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "fb update own" ON "public"."feedback" FOR UPDATE TO "authenticated" USING (("user_id" = "auth"."uid"()));
CREATE POLICY "program_access" ON "public"."ppl_index" USING (("auth"."uid"() = '80e70f14-aa0f-40ea-bad0-2f623fec5925'::"uuid")) WITH CHECK (("auth"."uid"() = '80e70f14-aa0f-40ea-bad0-2f623fec5925'::"uuid"));
CREATE POLICY "public read card_content" ON "public"."card_content" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "public read card_index" ON "public"."card_index" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "public read legi_index" ON "public"."legi_index" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "public read legi_profiles" ON "public"."legi_profiles" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "public read ppl_index" ON "public"."ppl_index" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "public read ppl_profiles" ON "public"."ppl_profiles" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "public read web_content" ON "public"."web_content" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "ref delete own" ON "public"."referrals" FOR DELETE TO "authenticated" USING (("code_owner" = ("auth"."uid"())::"text"));
CREATE POLICY "ref insert own" ON "public"."referrals" FOR INSERT TO "authenticated" WITH CHECK (("code_owner" = ("auth"."uid"())::"text"));
CREATE POLICY "ref select own" ON "public"."referrals" FOR SELECT TO "authenticated" USING (("code_owner" = ("auth"."uid"())::"text"));
CREATE POLICY "ref update own" ON "public"."referrals" FOR UPDATE TO "authenticated" USING (("code_owner" = ("auth"."uid"())::"text")) WITH CHECK (("code_owner" = ("auth"."uid"())::"text"));
CREATE POLICY "req auth delete" ON "public"."requests" FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "req auth insert" ON "public"."requests" FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "req auth read" ON "public"."requests" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "req auth update" ON "public"."requests" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "rt delete own" ON "public"."ratings" FOR DELETE TO "authenticated" USING (("user_id" = ("auth"."uid"())::"text"));
CREATE POLICY "rt insert own" ON "public"."ratings" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = ("auth"."uid"())::"text"));
CREATE POLICY "rt select own" ON "public"."ratings" FOR SELECT TO "authenticated" USING (("user_id" = ("auth"."uid"())::"text"));
CREATE POLICY "rt update own" ON "public"."ratings" FOR UPDATE TO "authenticated" USING (("user_id" = ("auth"."uid"())::"text")) WITH CHECK (("user_id" = ("auth"."uid"())::"text"));

-- Grants

GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon", "authenticated", "service_role";
GRANT ALL ON FUNCTION "public"."set_code_owner_text"() TO "anon", "authenticated", "service_role";
GRANT ALL ON FUNCTION "public"."set_user_id_text"() TO "anon", "authenticated", "service_role";
GRANT ALL ON FUNCTION "public"."set_user_id_uuid"() TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."bookmarks" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."bookmarks_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."card_content" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."card_content_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."card_index" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."ppl_agenda_cards_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."ppl_profiles" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."current ppl_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."feedback" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."feedback_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."impact" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."impact_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."legi_index" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."legi_index_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."legi_profiles" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."legi_overview_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."ratings" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."popularity_user_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."ppl_index" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."ppl_list_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."questions" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."q/a_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."referrals" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."referrals_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."requests" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."requests_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."subs" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."subs_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."users" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon", "authenticated", "service_role";
GRANT ALL ON TABLE "public"."web_content" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."web_content_id_seq" TO "anon", "authenticated", "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres", "anon", "authenticated", "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres", "anon", "authenticated", "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres", "anon", "authenticated", "service_role";
